---
- name: "Complete Cloudflare Setup: Add Domains & Create DNS Records"
  hosts: all
  gather_facts: yes

  tasks:
    - name: "Read domains"
      shell: cat domains.csv
      register: domains_content

    - name: "Read subdomains"
      shell: cat subdomains.csv
      register: subdomains_content

    - name: "Show loaded data"
      debug:
        msg: |
          DOMAINS:
          {{ domains_content.stdout }}

          SUBDOMAINS:
          {{ subdomains_content.stdout }}
