---
- name: "ðŸ”‘ STEP 4: Get Nameservers"
  hosts: all
  gather_facts: no
  
  tasks:
    - name: "Read zone mapping"
      shell: "cat /tmp/zone_mapping.txt"
      register: zone_mapping_raw

    - name: "Parse zones"
      set_fact:
        zone_pairs: "{{ zone_mapping_raw.stdout_lines | map('split', ',') | list }}"

    - name: "Query nameservers"
      shell: |
        ZONE_ID="{{ item[1] }}"
        
        curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${ZONE_ID}" \
          -H "X-Auth-Email: {{ cf_email }}" \
          -H "X-Auth-Key: {{ cf_api_key }}" \
          -H "Content-Type: application/json" | \
          python3 -c "import sys, json; d=json.load(sys.stdin); ns=d['result']['name_servers'] if d.get('result') else []; print('|'.join(ns))" 2>/dev/null
      register: nameservers_raw
      loop: "{{ zone_pairs }}"
      delay: 0.5
      ignore_errors: yes

    - name: "Save nameservers"
      shell: |
        cat > /tmp/nameservers_final.txt << 'NS_END'
        {% for i, item in enumerate(zone_pairs) %}
        {{ item[0] }},{{ nameservers_raw.results[i].stdout }}
        {% endfor %}
        NS_END

    - name: "Display nameservers"
      debug:
        msg: |
          â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
          âœ… STEP 4: NAMESERVERS RETRIEVED
          â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
          {% for i, item in enumerate(zone_pairs) %}
          Domain: {{ item[0] }}
          NS: {{ nameservers_raw.results[i].stdout.split('|') | join(', ') }}
          {% endfor %}
          â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
