---
- name: "Test Cloudflare Auth"
  hosts: all
  gather_facts: no
  timeout: 30
  
  tasks:
    - name: "Quick test"
      shell: |
        timeout 10 curl -s -X GET "https://api.cloudflare.com/client/v4/zones?per_page=1" \
          -H "X-Auth-Email: {{ cf_email }}" \
          -H "X-Auth-Key: {{ cf_api_key }}" \
          -H "Content-Type: application/json" | \
          python3 -c "import sys, json; d=json.load(sys.stdin); print('✅ Auth OK' if d.get('success') else '❌ Auth Failed')" 2>/dev/null || echo "❌ API Error"
      register: result
      timeout: 15

    - name: "Result"
      debug:
        msg: "{{ result.stdout }}"
